### ISSUE TITLE
WS-Security

### ISSUE THREAD

**Issue by alexsantos** [AirAsiaExpedia/node-foam#2]
Hi. This module is what I've been looking for :+1:  A simple and well written SOAP client with very smart choises.
What I need is WS-Security (PasswordText) so I already forked your repo and will send a PR with that (hope soon).
I use JSLint on my code - do you mind if I change one thing or another?

Alex

**Comment by jtblin** [comment]
Glad to hear this is useful for you and that you want to add support for WS-Security. 
Re: style changes (I assume that's what you mean by JSLint), can you please detail which change you want to do so that we can agree on what to and not to change?

**Comment by AlexSantos** [comment]
Hi.
To make things more modular, I instead created a module just for the ws-security feature (it's already visible on my GitHub account) and then use it here.
JSLint alerts for a lot of issues, mainly style and function ordering (functions that are called below). Apart these cases, there is an alert on the for loop (line 70) for the lack of the hasOwnProperty check and on the gzunip function (line 80) because the name gunzip is used also for the local variable.
I myself tend to pass all my code throught JSLint (sublime is great). And I'm a big fan of Douglas Crockford :-)

**Comment by AlexSantos** [comment]
Update: JSHint is much more "permissive" to style so it only alerts for those two things I mentioned above.
I'll do a PR from JSHint alerts.
